services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: username
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"